In [1]:
import torch 
import numpy as np #numpy 是用于科学计算的库

In [2]:
#对张量进行初始化
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
#使用numpy处理数组
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
#新的张量会继承原始张量的属性，但也可以被重写
x_ones = torch.ones_like(x_data)  # 保留原有属性的情况
print(f"Ones Tensor: \n {x_ones} \n")

# 覆盖原有属性的情况
x_rand = torch.rand_like(x_data, dtype=torch.float) #使用torch.rand_like()创建具有随机值的张量
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9697, 0.5109],
        [0.0869, 0.3475]]) 



In [5]:
shape = (2, 3,) #张量维度的元组
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5021, 0.7860, 0.5928],
        [0.4804, 0.8009, 0.4877]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
tensor = torch.rand(3, 4) #创建一个3x4的张量，其中元素是在0到1之间的随机数

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")#张量存储在cpu上

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [7]:
# 对张量进行索引和切片 Standard numpy-like indexing and slicing
tensor = torch.ones(4, 4)#创建一个4x4的张量，元素都是1
print(f"First row: {tensor[0]}")#输出第一行，从位置0开始
print(f"First column: {tensor[:, 0]}")#输出第一列，从位置0开始
print(f"Last column: {tensor[..., -1]}")#输出最后一列，-1表示最后一个元素
tensor[:, 1] = 0#将第二列的所有元素设置为0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [8]:
# 联合张量 Joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)#按照指定维度将三个张量拼接在一起
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [9]:
# 算术运算 Arithmetic operations
# 计算两个张量之间的矩阵乘法 This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# 返回转置后的结果``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# 计算元素之间的乘积 This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)#mul()函数将两个张量相乘,mul = multiple

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [10]:
# 单一元素张量 Single-element tensors
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [11]:
# 就地操作 In-place operations 
# 就地操作直接在原始张量上进行操作，而不是创建一个新的张量
# In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [12]:
t = torch.ones(5)
print(f"t: {t}")#输出张量的值
n = t.numpy()  # 将张量转换为numpy数组，转换后的NumPy数组与原始张量共享相同的内存空间
print(f"n: {n}")#输出数组的值

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [13]:
# NumPy数组与原始张量共享相同的内存空间，改变张量的值也会改变数组的值
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [14]:
#数组的变化也会反映在张量上
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
